name: Deploy to AWS Lambda using OIDC

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.4.0

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        AWS_REGION: us-east-1
        AWS_ROLE_ARN: arn:aws:iam::677276078111:role/GitHubActionsDeployRole  # ARN of the role
        AWS_WEB_IDENTITY_TOKEN_FILE: ${{ github.event.head_commit.id }}  # GitHub OIDC Token
